### ISSUE TITLE
[PY] FP numbers are serialized as decimals

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#3396]
This is wrong, for 2 reasons:
- the precision supported is different.
- FP has some special values which cannot be represented, such as Infinity and NaN

**Comment by mihaibudiu** [comment]
In Java for the Rust target we encode FP using a binary serialization which is lossless:
```
int exact = Float.floatToRawIntBits(value);
String f32 = "f32::from_bits(" +
            Integer.toUnsignedString(exact) + "u32)";
```

**Comment by abhizer** [comment]
Only results of ad-hoc queries are parsed as decimals, the outputs of normal views get parsed correctly (FPs get parsed as Float32 and Float64), as the schema is available.

I am not sure how to correctly represent FPs from ad-hoc queries because we do not have the schema information.

Also, python's decimal (`decimal.Decimal`) type can represent values such as `Infinity` and `NaN`.

**Comment by mihaibudiu** [comment]
Can you add some tests with infinity and then close the issue if they work?

**Comment by mihaibudiu** [comment]
This is either a serious bug in datafusion, or maybe you didn't write the correct program.
Make sure you cast the values to DOUBLE.
0.0 is a DECIMAL in SQL, which does not have Infinity.

**Comment by abhizer** [comment]
Ad-hoc queries in web console: 

<img width="756" alt="Image" src="https://github.com/user-attachments/assets/5f06096a-4dc5-4420-bdee-6572f0987aa8" />

**Comment by mihaibudiu** [comment]
The question is whether this is a bug in our webconsole or in datafusion itself
Maybe we can't properly display NaN because of Javascript?

**Comment by lalithsuresh** [comment]
You can test using fda too.

**Comment by abhizer** [comment]
This is a bug in the JSON format of ad-hoc query API.

For the query: `select cast('Infinity' as double)`

`format=json` returns `null`
```sh
➜  curl http://localhost:8080/v0/pipelines/blah/query\?sql\=select%20cast%28%27Infinity%27%20as%20double%29\&format\=json
{"Utf8(\"Infinity\")":null} 
```

`format=text` returns `inf`
```sh
➜  curl http://localhost:8080/v0/pipelines/blah/query\?sql\=select%20cast%28%27Infinity%27%20as%20double%29\&format\=text
+------------------+
| Utf8("Infinity") |
+------------------+
| inf              |
+------------------+%
```

**Comment by mihaibudiu** [comment]
I have assigned @gz as well

**Comment by gz** [comment]
can you check if this is now supported by using the arrow-ipc format for ad-hoc queries (it probably should)

**Comment by mihaibudiu** [comment]
@abhizer when you get some time, can you please check whether the Python SDK can use the arrow-ipc format to move data losslessly from fda?

**Comment by mihaibudiu** [comment]
@abhizer is this issue fixed?

**Comment by abhizer** [comment]
Not yet, https://github.com/feldera/feldera/pull/4226 should fix it.

**Comment by rivudhk** [comment]
Cannot supply **Infinity** or **NaN** as input for FP types using Python SDK as it produces parse error such as:

> **>           raise FelderaAPIError(str(err), request) from err
> E           feldera.rest.errors.FelderaAPIError: FelderaError. Error message: 
> E           Error Code: ParseErrors
> E           Message: Errors parsing input data (1 errors):
> E               Parse error: failed to parse string as a JSON document: expected value at line 1 column 10
> E           Invalid fragment: '[{"dbl": Infinity}]'**

When supplying following as input for FP column:

1. Infinity : **math.inf** OR **float("inf")** OR **np.inf** 
2. NaN : **math.nan** OR **float("nan")** OR **np.nan**

**Comment by abhizer** [comment]
> Cannot supply Infinity or NaN as input for FP types

This is a backend error where it fails to parse `Infinity` as float. I believe you have to input it as `"Infinity"`, as a string.
https://github.com/serde-rs/json/issues/838

I believe we would have to either use something like: https://docs.rs/serde_json5/latest/serde_json5/ or go through the entire dataset in python to convert each and every Infinity, NaN to string.

This should be a separate backend issue.

**Comment by mihaibudiu** [comment]
I will close this issue and open another one. 
The python SDK is now fine with respect to floating point, but fda/ad-hoc queries are still not.
